/**
 * This file was automatically generated by the Mule Development Kit
 */
package com.mulesoft.module.fileutils;

import org.mule.api.MuleEvent;
import org.mule.api.client.MuleClient;
import org.mule.construct.Flow;
import org.mule.tck.FunctionalTestCase;
import org.mule.tck.AbstractMuleTestCase;

import org.junit.Test;

@SuppressWarnings("deprecation")
public class FileUtilsModuleTest extends FunctionalTestCase
{
    @Override
    protected String getConfigResources()
    {
        return "mule-config.xml";
    }

    @Test
    public void testFlow() throws Exception
    {
        MuleClient client = muleContext.getClient();
        client.send("vm://vm.in", "", null);
    }

 }
